[package]
name = "centroid-calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib", "rlib"]
